# Generated by Django 4.1.5 on 2023-03-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productturu',
            name='product',
        ),
    ]
