# Generated by Django 4.1.5 on 2023-03-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_remove_productturu_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='gander',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug Kategori'),
        ),
    ]
