# Generated by Django 4.1.5 on 2023-03-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_gander_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeletter',
            name='productTuru',
        ),
        migrations.AddField(
            model_name='product',
            name='productTuru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.productturu', verbose_name='Ürün Türü'),
        ),
    ]
