# Generated by Django 4.1.5 on 2023-03-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_remove_sizeletter_productturu_product_productturu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeletter',
            name='gander',
        ),
        migrations.RemoveField(
            model_name='sizeletter',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='gander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.gander', verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Fiyat'),
        ),
    ]
