# Generated by Django 4.1.5 on 2023-03-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_remove_sizeletter_gander_remove_sizeletter_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='sizeletter',
            name='price',
            field=models.FloatField(default=0, verbose_name='Fiyat'),
        ),
    ]
