# Generated by Django 4.1.5 on 2023-03-31 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0007_remove_product_price_sizeletter_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_all', models.FloatField(default=0, verbose_name='Toplam Fiyat')),
                ('count', models.IntegerField(default=0, verbose_name='Toplam Adet')),
                ('sizeletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.sizeletter', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
