# Generated by Django 4.1.5 on 2023-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbasket',
            name='date_now',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Saat'),
        ),
    ]
