# Generated by Django 4.1.5 on 2023-04-02 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_alter_product_productturu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeletter',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appMy.size', verbose_name='Beden'),
        ),
    ]
