# Generated by Django 4.1.5 on 2023-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='deneyim',
            field=models.IntegerField(default='-', verbose_name='Deneyim'),
        ),
    ]
